### ISSUE TITLE
Make it so that every wrong answer removes 100 points

### ISSUE THREAD

**Issue by TechStudent10** [KendallDoesCoding/quiz#1]
Then all you have to do to calculate the number of wrong answers is:
```js
((total amount of questions * 100) - score) / 100
```

So if I had 15 questions and my score was 1000 then:
```js
((15 * 100) - 1000) / 100
```
would give you 5. Then `15 - 5 = 10`. So 5 wrong answers and 10 correct answers.

Okay so it's a bit complicated but I think this could be an interesting game mechanic.

**Comment by KendallDoesCoding** [comment]
Interesting, sorry for late reply, unwatched this repo by mistake. Can you make a PR?

**Comment by KendallDoesCoding** [comment]
@TechStudent11 Transferred it as I wanted to remove the contributors on quiz, they didnt help out with the project.. I was just testing the co-authors feature.. Transfering back.

**Comment by KendallDoesCoding** [comment]
> @TechStudent11 Transferred it as I wanted to remove the contributors on quiz, they didnt help out with the project.. I was just testing the co-authors feature.. Transfering back.

@TechStudent11 I can't transfer it back for some reason, but please work on this here: https://github.com/KendallDoesCoding/quiz

**Comment by KendallDoesCoding** [comment]
> > @TechStudent11 Transferred it as I wanted to remove the contributors on quiz, they didnt help out with the project.. I was just testing the co-authors feature.. Transfering back.
> 
> @TechStudent11 I can't transfer it back for some reason, but please work on this here: https://github.com/KendallDoesCoding/quiz

Figured the issue.

**Comment by KendallDoesCoding** [comment]
You know how to do this right? I dont know JS lol.

**Comment by TechStudent10** [comment]
> You know how to do this right? I dont know JS lol.

Sorry. I made this issue a long time ago and now am trying to figure out what the math was.

Anyways, yeah I could create a PR if you want. But I don't get how you made this app without knowing JS. That's a little weird.

**Comment by KendallDoesCoding** [comment]
> > You know how to do this right? I dont know JS lol.
> 
> Sorry. I made this issue a long time ago and now am trying to figure out what the math was.
> 
> Anyways, yeah I could create a PR if you want. But I don't get how you made this app without knowing JS. That's a little weird.

Oh ok.

Yeah please make a PR, I mostly followed a tutorial for this app. but added my own menus, etc lol. So, I know those basic JS concepts, but not entirely.

**Comment by KendallDoesCoding** [comment]
> > > You know how to do this right? I dont know JS lol.
> > 
> > 
> > Sorry. I made this issue a long time ago and now am trying to figure out what the math was.
> > Anyways, yeah I could create a PR if you want. But I don't get how you made this app without knowing JS. That's a little weird.
> 
> Oh ok.
> 
> Yeah please make a PR, I mostly followed a tutorial for this app. but added my own menus, etc lol. So, I know those basic JS concepts, but not entirely.

Can you work on #4 too?

**Comment by KendallDoesCoding** [comment]
@TechStudent11 Are you still working on this or did what you say in https://github.com/KendallDoesCoding/mogul-christmas/issues/80 apply here too?

**Comment by TechStudent10** [comment]
nah to both. it's really simple to implement, so I think you can do it

**Comment by KendallDoesCoding** [comment]
Ok will try. I just added a new topic question (not yet committed, but
added on remote) so I'm currently working on the quiz itself lol

**Comment by KendallDoesCoding** [comment]
It would help if you do it but yeah as I said, I'll try it.... Unassigning.

**Comment by KendallDoesCoding** [comment]
Hey @vrindavan , I require this done for all the quizzes, which can be seen in https://quiz.kendalldoescoding.gq/topics/ you did it only for the main one.

**Comment by BrajBliss** [comment]
I didn't realise haha. I don't have time these days but I'll check out and try to edit from GitHub itself.

**Comment by BrajBliss** [comment]
Assign this to me, I am editing each js file. It is not a good practice though. This is very redundant. Then there would be adding whitespace to the icons on the rule page as I did previously but I do not have time for that so I will just add a deduction function to every other.

**Comment by KendallDoesCoding** [comment]
Done in #13

**Comment by KendallDoesCoding** [comment]
> I am editing each js file. It is not a good practice though. This is very redundant.

Yeah, I know that but the issue is, I need so many HTML, CSS, JS files and different folders because I need it to link back properly on the JS, plus the content on some of the files are different.

JS I surely require so many files because the questions are different? But maybe it is possible to const question for a certain quiz, and make like 15 or so const and then link the const to the HTML? I'm not good at JS but maybe it is possible.

**Comment by BrajBliss** [comment]
You can create one JSON file for all quizzes and then use js to link all of them in one.

**Comment by KendallDoesCoding** [comment]
No worries. Thanks
