### ISSUE TITLE
Adding whitespace to icons on the home page

### ISSUE THREAD

**Issue by BrajBliss** [KendallDoesCoding/quiz#14]
There is no whitespace between title and icon in some places. Just need to add one space after the title. For example the below screenshot:

![image](https://user-images.githubusercontent.com/50140643/180835823-c6cd7409-8e9a-422c-88a9-d71bb04a3879.png)

This is one of the many.

**Comment by KendallDoesCoding** [comment]
Thanks for bringing to my notice, can you work on this.

**Comment by BrajBliss** [comment]
I cannot promise, very busy these days but might on this weekend.

**Comment by KendallDoesCoding** [comment]
> I cannot promise, very busy these days but might on this weekend.

It's basic css so I'll try.

**Comment by sivuyilemene** [comment]
Hi. Is this issue still open? I would like to work on it.

**Comment by KendallDoesCoding** [comment]
Yes, it is. Sure! You can work on it..

**Comment by BrajBliss** [comment]
Good to know it's done.
