### ISSUE TITLE
Updating the Rules HTML File

### ISSUE THREAD

**Issue by BrajBliss** [KendallDoesCoding/quiz#15]
After adding a rule of -100 for each wrong answer, the rules also need to be updated for each topic.

Reference: #13 #1

**Comment by KendallDoesCoding** [comment]
> After adding a rule of -100 for each wrong answer, the rules also need to be updated for each topic.
> 
> Reference: #13 #1

Will work on this.

**Comment by KendallDoesCoding** [comment]
Oops, forgot about this, will get to work.

**Comment by KendallDoesCoding** [comment]
@vrindavan Can you only do this 🤣 ?

**Comment by KendallDoesCoding** [comment]
It seems that this is already done actually, but there is a small grammer issue in the wordings, so I will just fix it.

I don't remember when this was done 😆
