### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by Hachikoi-the-creator** [KendallDoesCoding/quiz#16]
UI breaks at 14' and less, make the font as well as the size of the elements responsive

**Comment by KendallDoesCoding** [comment]
> UI breaks at 14' and less, make the font as well as the size of the elements responsive

Can you please share a screenshot?

**Comment by Hachikoi-the-creator** [comment]
oh yeah mb, the H1 get's cut above, and option buttons overflow in mobile, testing on firefox
https://ibb.co/LQdqBZc
https://ibb.co/Y710Yjy

**Comment by KendallDoesCoding** [comment]
Oh yea. I knew this from a long time, it works well on Android mostly but
has issues on Apple devices. But this is the preview from the browser, on
the actual device you can move to see the full text. I tried making it
responsive but that didn't work. If you can help with this, it will be
great.

**Comment by Hachikoi-the-creator** [comment]
yeah my idea was to fix it!

**Comment by KendallDoesCoding** [comment]
Sorry, my bad in revieweing, please check out #19 @Hachikoi-the-creator

**Comment by KendallDoesCoding** [comment]
@Hachikoi-the-creator can you work on this but without doing the same mistake as last time.. I'm really sorry that I had to revert it, but it was messing up the website.

Please do testing locally before making the PR :)

**Comment by Hachikoi-the-creator** [comment]
I'd love to but I have no idea why the styles were breaking/not loading

**Comment by KlausMikhaelson** [comment]
Hey @KendallDoesCoding if it's not resolved than can I work on it ?

**Comment by KendallDoesCoding** [comment]
Sure.

**Comment by KendallDoesCoding** [comment]
> I'd love to but I have no idea why the styles were breaking/not loading

Neither do I, lol. Hopefully @KlausMikhaelson can help us if that's fine with you!!

**Comment by KlausMikhaelson** [comment]
Hey @KendallDoesCoding ig this project needs some documentation on how to set it up locally
I am opening an issue can you check it out ?

**Comment by KendallDoesCoding** [comment]
> Hey @KendallDoesCoding ig this project needs some documentation on how to set it up locally I am opening an issue can you check it out ?

Yup!

**Comment by Hachikoi-the-creator** [comment]
I don't remeber where I saw it, but I found a solution for the local developent
https://www.npmjs.com/package/serve
tl:dr
$ npm i serve --location=global
- inside the project folder
$ serve

Nvm somehow doing that makes the whole app unable to retrieve the app.js in any page

**Comment by KendallDoesCoding** [comment]
fixed in [136bfe1](https://github.com/KendallDoesCoding/quiz/commit/136bfe1c51f1f6911a1b42c6221c5189b98646cb)
