### ISSUE TITLE
Quiz Topic: Instruments

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#2]
Adding to wiki, possible quiz topic

**Comment by KendallDoesCoding** [comment]
Maybe also another one for instruments?

**Comment by KendallDoesCoding** [comment]
> Maybe also another one for instruments?

Yeah, can't find interesting music quiz questions.

**Comment by AnkitAnandMastery17** [comment]
Hey! Is this issue still open? If yes, please assign it to me.

**Comment by KendallDoesCoding** [comment]
> Hey! Is this issue still open? If yes, please assign it to me.

Yes. Assigned to you.

**Comment by SyonKuppili** [comment]
Hey! If Ankit isn't working on this, could I please get assigned for this?

**Comment by AnkitAnandMastery17** [comment]
I am working on this.

**Comment by KendallDoesCoding** [comment]
fixed in #75
