### ISSUE TITLE
[Javascript] Tech Quiz not working.

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#21]
User can't enter tap the answer and enter it for the "[Tech Quiz](https://quiz.kendalldoescoding.gq/tech/game/)". I think this means that there is a issue with the JS?

Please debug and fix at the earliest.

@TechStudent10 can you have a look?

**Comment by TechStudent10** [comment]
I recommend looking at the DevTools before coming to me or others.

![image](https://user-images.githubusercontent.com/76978184/186515599-6926fc40-a714-428f-af59-492d6da4836b.png)

Looks like this has come from #1

**Comment by KendallDoesCoding** [comment]
> I recommend looking at the DevTools before coming to me or others.
> 
> ![image](https://user-images.githubusercontent.com/76978184/186515599-6926fc40-a714-428f-af59-492d6da4836b.png)
> 
> Looks like this has come from #1

I forgot to do it this time, sorry. But actually, it isn't even showing up in my DevTools now, I use Chrome, idk why.

**Comment by KendallDoesCoding** [comment]
@TechStudent10 What is the issue though? Can you make a PR?

**Comment by KendallDoesCoding** [comment]
> But actually, it isn't even showing up in my DevTools now, I use Chrome, idk why.

Lol, the quiz is working now for 1 question but stops after and then only do I get the error. Will see if I can fix it.
