### ISSUE TITLE
Major restructure of folders, files, etc.

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#22]
Currently, for every quiz I have a folder, in which includes the suggestion, end, game, rules directory. Although it gets very inconvenient for contributors and me personally to make edits to all the quizzes at once.

The reason I did this was so the website url is linked backed to the quiz you were playing it, but ig that's not really required, **so we can link the suggestion and end back to the main directory.**

Although, for the game directory, the questions change per quiz (common sense) and the game.js in that directory have the questions listed, **so would it be possible that in the main js file, to const a bunch of elements for the respective quizzes and link back the element of the quiz somehow?** I'm not good at JS so idk if this is possible lol.

Rules also change for every quiz, so should we const the rules page via JS too?

Other suggestions will be very appreciated.

cc: @vrindavan @TechStudent10

**Comment by BrajBliss** [comment]
I do not have time but I have commented here: https://github.com/KendallDoesCoding/quiz/issues/1#issuecomment-1227454328

**Comment by KendallDoesCoding** [comment]
> I do not have time but I have commented here: [#1 (comment)](https://github.com/KendallDoesCoding/quiz/issues/1#issuecomment-1227454328)

Ok, I will try following your method, but may need some help from someone.

**Comment by ghost** [comment]
Can I work on this issue

**Comment by KendallDoesCoding** [comment]
> Can I work on this issue

thanks

**Comment by KendallDoesCoding** [comment]
> Can I work on this issue

Sure!

**Comment by Hachikoi-the-creator** [comment]
since this is still up can I reduce all the CSS? like putting it all in a single /css dir
that could hopefully fix the live server issues and make everything lighter

also would like to remove the final dir that every index.html is inside
like so:

browsers/end/index.html -> pages/browsers_end.html ?

**Comment by Hachikoi-the-creator** [comment]
I made a deployment of the branch I'm working on
currently I just have the first quiz working, and the extra pages like suggestions etc...
https://8koi-rework-branch.netlify.app/

**Comment by KendallDoesCoding** [comment]
Yes. You can do this, as it will really keep things formated and in place.

I was going to do this, but it would take a lot of time and I was little
busy the last couple of weeks.

**Comment by KendallDoesCoding** [comment]
Will have a look when I'm on my laptop.

**Comment by KendallDoesCoding** [comment]
@Hachikoi-the-creator just to clarify, you are making the following changes:


- Combining all the CSS for the quizzes in one file
- browsers/end/index.html -> pages/browsers_end.html

If you need any help, please let me know.

Thanks,
KendallDoesCoding

**Comment by Hachikoi-the-creator** [comment]
I'm kinda stuck whit how to minimize the JS, since makes the whole thing easier to mantain 
I'm thinking about using a class but not sure how to implement it, will be doing some testing in the meantime
and that format for pages would look kinda ugly so I opted for

- pages/browsers/index.html
- pages/browsers/game.html

instead, moving the js to a single file/class would allow to only need 2 html files !

**Comment by Hachikoi-the-creator** [comment]
Holy moly, this was a lot lmao
I was just taking a rest from C now going back unu

**Comment by KendallDoesCoding** [comment]
fixed in [136bfe1](https://github.com/KendallDoesCoding/quiz/commit/136bfe1c51f1f6911a1b42c6221c5189b98646cb)
