### ISSUE TITLE
[BUG] Website not opening locally

### ISSUE THREAD

**Issue by KlausMikhaelson** [KendallDoesCoding/quiz#23]
When I try to open the website locally, using a VS code extension called Liveserver, I get the error `cannot get route`.

**Comment by KendallDoesCoding** [comment]
# OUTDATED (as issue was updated 22 hours after creation!)

Good idea, but doesn't the user just need to run .html for the file to work and everyone interested in this project would know that? 

People who code in .html and who want to contribute, would surely know of the VS Code Extension - Live Server, or the user can refresh the page locally to see if their edits worked before making a PR.

So, I don't think we should do this as of now, but please share your thoughts.

Thanks,
Kendall Does Coding

**Comment by KlausMikhaelson** [comment]
Yeah even I know how html works in the liveserver so I tried to start in the liveserver and click on one of the options in the homepage but than it was showing `cannot get route`

**Comment by KendallDoesCoding** [comment]
uh weird, it works well for me.

*screenshot please*

**Comment by ShaikMoAbdullah** [comment]
Hi all, I have checked locally in my system. Works well for me.

**Comment by KlausMikhaelson** [comment]
Ooo okay I did something wrong will update here

**Comment by KendallDoesCoding** [comment]
> Hi all, I have checked locally in my system. Works well for me.

Hi Shaik.. Thanks for checking that for us!

@KlausMikhaelson , yes please update on what issue your facing exactly, and share screenshots.. If it's fixed, please close this issue.

**Comment by KendallDoesCoding** [comment]
@KlausMikhaelson Please update on if the issue has been fixed.

**Comment by KendallDoesCoding** [comment]
fixed in [136bfe1](https://github.com/KendallDoesCoding/quiz/commit/136bfe1c51f1f6911a1b42c6221c5189b98646cb)
