### ISSUE TITLE
Add a Issue Template

### ISSUE THREAD

**Issue by ChinmayMhatre** [KendallDoesCoding/quiz#24]
Adding a template could help the contributors express their requirements better

**Comment by KendallDoesCoding** [comment]
A PR template is already in place, ig you mean a Issue template?

**Comment by ChinmayMhatre** [comment]
> A PR template is already in place, ig you mean a Issue template?

Yes! an issue template.

**Comment by ChinmayMhatre** [comment]
I could create them as well.

**Comment by ChinmayMhatre** [comment]
templates for features, documentation and bugs would be useful.

**Comment by KendallDoesCoding** [comment]
> I could create them as well

Sure! Assigning you

**Comment by KendallDoesCoding** [comment]
> templates for features, documentation and bugs would be useful.

Yeah, I know. I got issue templates in my other repos which you can copy, paste to this repo.
