### ISSUE TITLE
Quiz Topic: Ram/Computer Parts

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#3]
Can add a bunch of questions about Ram/Computer Parts

RAM QUIZ: https://letsfindcourse.com/computer-fundamentals-mcq/ram-mcq-questions-and-answers#:~:text=Explanation%3A%20RAM%20Stands%20for%20Random%20Access%20Memory.
COMPUTER PARTS QUIZ: need to do research

**Comment by KendallDoesCoding** [comment]
adding this to the wiki

**Comment by MOHDNEHALKHAN** [comment]
@KendallDoesCoding Please assign this issue to me, I want to work on it

**Comment by AnkitAnandMastery17** [comment]
Hey! Is this issue still open? If yes, please assign it to me.

**Comment by KendallDoesCoding** [comment]
@MOHDNEHALKHAN - sorry, missed out your message. Do you still want to work on this or should I assign it to @AnkitAnandMastery17?

**Comment by MOHDNEHALKHAN** [comment]
@KendallDoesCoding, assign me as I am free to work on this feature.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding, assign me as I am free to work on this feature.

Ok.

@AnkitAnandMastery17 - you can add any quiz topic of your choice, without creating a issue and make a PR if I like the questions, I will merge the PR.

**Comment by KendallDoesCoding** [comment]
Assigned you @MOHDNEHALKHAN

**Comment by MOHDNEHALKHAN** [comment]
@KendallDoesCoding, In the Technology section can I add a computer parts quiz before working on this feature?

![Screenshot 2023-07-24 151637](https://github.com/KendallDoesCoding/quiz/assets/125626654/cab4d778-093c-4c57-9b0d-b32c7a724194)

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding, In the Technology section can I add a computer parts quiz before working on this feature?
> 
> ![Screenshot 2023-07-24 151637](https://user-images.githubusercontent.com/125626654/255553187-cab4d778-093c-4c57-9b0d-b32c7a724194.png)

Hey, the topics in "topics" page should link to something. I suggest you create the quiz first and with that same PR you add it in the topics page as that is part of creating the quiz.

But, if you prefer, yes you can create a PR of adding it to the topics page, but I will only merge that along with the computer parts quiz.
