### ISSUE TITLE
Quiz Topic: Programming Language

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#34]
programming language related quiz

_Originally posted by @Srinja333 in https://github.com/KendallDoesCoding/quiz/issues/32#issuecomment-1467533414_

**Comment by SrinjayKapri7** [comment]
same code output  related mcq, some core cocept related mcq

**Comment by Akbar-Ahmed** [comment]
Hello @KendallDoesCoding  so in this project there is a requirement for adding a quiz on programming language? Am i correct?

**Comment by KendallDoesCoding** [comment]
yup

*Thanks,*
*Kendall Does Coding*

*Portfolio
<https://cdc-aims.com/click?redirect=https%3A%2F%2Fkendalldoescoding.gq&dID=1678988301785&hashId=060de6478a47358f5315814fdd49f493dff92988d90dca1ba25e30911a8a60f18777e7&linkName=Portfolio>*
*Github
<https://cdc-aims.com/click?redirect=https%3A%2F%2Fgithub.com%2FKendallDoesCoding&dID=1678988301785&hashId=060de6478a47358f5315814fdd49f493dff92988d90dca1ba25e30911a8a60f18777e7&linkName=Github>*
*Youtube*
<https://cdc-aims.com/click?redirect=https%3A%2F%2Fkendalldoescoding.gq%2FcodingYT&dID=1678988301785&hashId=060de6478a47358f5315814fdd49f493dff92988d90dca1ba25e30911a8a60f18777e7&linkName=Youtube>

**Comment by Akbar-Ahmed** [comment]
Hey, can you advise where do you want this quiz data to be added.
I have checked other quiz as well but it shows the site can't be reached error.

**Comment by KendallDoesCoding** [comment]
> I have checked other quiz as well but it shows the site can't be reached error.

Please create a issue in the GitHub providing screenshots.

You must create a quiz in `pages`, make a new directory, link CSS from css directory. Make a new directory in `.js/data`, add the questions and then link it back to HTML.
