### ISSUE TITLE
[BUG] [URGENT] Always showing b option as correct even if incorrect. - URGENT ASSISTANCE REQUIRED

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#35]
In the website I found one bug I don't know if the bug coming for me only. The bug is if we select the b option for any questions It is giving correct and that is also not the actual answer.

_Originally posted by @Darshanjaji in https://github.com/KendallDoesCoding/quiz/issues/32#issuecomment-1468048670_

**Comment by KendallDoesCoding** [comment]
@Hachikoi-the-creator I think this is a issue that got caused after the major rework, any idea how to fix this?

**Comment by Darshanjaji** [comment]
Any logical problem In the code?

**Comment by KendallDoesCoding** [comment]
> Any logical problem In the code?

I haven't gotten a chance to take a deep look just now, but this is caused due to the Major Rework ( #22 ) where we restructured the files, instead of being in many directories/many files, we cut them down to one directory and few files.

Because of how big the work of the restructure was, it was bond to a few small errors. I don't think this is a big issue code related, it may just be a small thing and a easy fix if we figure out what's going on.

I didn't notice the bug at all. Thanks so much for bringing this to my notice @Darshanjaji , because if the game is like this. it's not playable at all. We must work and fix this ASAP.

Thanks,
KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
I have put the website on maintenance  until this is fixed or the game is unplayable.

**Comment by TripleStarCodeHunter** [comment]
Hey can you assign this issue to me. I'm almost done rectifying the error and will be submitting a pull request real soon

**Comment by TripleStarCodeHunter** [comment]
Hey can you assign this issue to me. I'm almost done rectifying the error and will be submitting a pull request real soon
@KendallDoesCoding

**Comment by Hachikoi-the-creator** [comment]
was too busy with a bootcamp, but hey good thing it got fixed!

**Comment by KendallDoesCoding** [comment]
no worries. i hope you enjoyed the bootcamp.

it was just a slight error. glad Bilai could fix it!!

*Thanks,*
*Kendall Does Coding*

*Portfolio
<https://imadeia.com/click?redirect=https%3A%2F%2Fkendalldoescoding.gq&dID=1679413339522&hashId=060de6478a47358f5315814fdd49f493dff92988d90dca1ba25e30911a8a60f18777e7&linkName=Portfolio>*
*Github
<https://imadeia.com/click?redirect=https%3A%2F%2Fgithub.com%2FKendallDoesCoding&dID=1679413339522&hashId=060de6478a47358f5315814fdd49f493dff92988d90dca1ba25e30911a8a60f18777e7&linkName=Github>*
*Youtube*
<https://imadeia.com/click?redirect=https%3A%2F%2Fkendalldoescoding.gq%2FcodingYT&dID=1679413339522&hashId=060de6478a47358f5315814fdd49f493dff92988d90dca1ba25e30911a8a60f18777e7&linkName=Youtube>

**Comment by Hachikoi-the-creator** [comment]
Oh yeah and just saw the credits in the readme! Thank you!! :heart:
