### ISSUE TITLE
Play music in background instead of redirecting to YouTube

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#39]
Refer to: https://www.tutorialspoint.com/How-to-add-background-music-in-HTML#:~:text=The%20HTML%20tag%20is,play%20music%20in%20the%20background.

**Comment by Rithik14** [comment]
Hey can i work on this issue..

**Comment by Rithik14** [comment]
can you pls assign me this issue..

**Comment by KendallDoesCoding** [comment]
Sure @Rithik14

**Comment by Rithik14** [comment]
```html
<!DOCTYPE html>
<html> 
<head>
    <title>
      HTML <bgsound> Tag
  </title>
</head>
<body>
    <center>
        <h2>HTML <bgsound> tag</h2>
        <bgsound src="https://media.geeksforgeeks.org/wp-content/uploads/20190531135120/beep.mp3" />
         <p>please plugin speaker/headphone to listen to the sound.</p>
    </center>
</body>
</html>
```

**Comment by Rithik14** [comment]
Is this correct way to answer..

**Comment by Rithik14** [comment]
# **Related Issue/Play music in background instead of redirecting to YouTube**

fixes #39

## Code snippet

```html
<!DOCTYPE html>
<html> 
<head>
    <title>
      HTML <bgsound> Tag
  </title>
</head>
<body>
    <center>
        <h2>HTML <bgsound> tag</h2>
        <bgsound src="https://media.geeksforgeeks.org/wp-content/uploads/20190531135120/beep.mp3" />
         <p>please plugin speaker/headphone to listen to the sound.</p>
    </center>
</body>
</html>
```

**Comment by Rithik14** [comment]
Is this way is correct..

**Comment by KendallDoesCoding** [comment]
If it plays the music in the browser, then yes! @Rithik14 .

**Comment by KendallDoesCoding** [comment]
pls make a PR.

**Comment by Rithik14** [comment]
Dude but this `<bgsound>` tag supports only for Internet Explorer not for other browsers .so can i use `<audio>` tag instead of `<bgsound>`

**Comment by Rithik14** [comment]
Hey can use audio tag..

**Comment by Rithik14** [comment]
Hey can i use audio tag

**Comment by KendallDoesCoding** [comment]
> Reference

Sure.

**Comment by Rithik14** [comment]
Hey if any issues in code pls let me now

**Comment by Rithik14** [comment]
Hey if any issues in my code pls let me now

**Comment by aaryansr26** [comment]
Hey @Rithik14 did you solve this?

**Comment by Rithik14** [comment]
> 

ya dude i have solved...but i am not sure about my pull req 
if any mistakes in my code pls let me now

**Comment by aaryansr26** [comment]
He said that music is not playing in one of the comments in your pull request @Rithik14!
I think when you'll refresh the page, the music will stop playing because of some feature they added onto the audio element. 
Instead I have added some buttons which can control the output of the music, and can be paused or played anytime on the background!
If you like this solution I can show it to you! @Rithik14 @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
@Rithik14 - are you fine if I accept @aaryansr26 's PR?

**Comment by Rithik14** [comment]
> @Rithik14 - are you fine if I accept @aaryansr26 's PR?
> 

Fine dude

**Comment by KendallDoesCoding** [comment]
> > @Rithik14 - are you fine if I accept @aaryansr26 's PR?
> 
> Fine dude

I am very sorry for the inconvenience, hope you can contribute to this project.

**Comment by Rithik14** [comment]
> project

No problem dude
