### ISSUE TITLE
[FEATURE REQUEST] Figure new points when answer correct/wrong for points distribution

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#4]
For now, when the answer is right, a figure like +100 in green should so up above the points. After #1 is done, a figure like -100 should show for every wrong answer.

@TechStudent10, can you work on this/merge this with the PR of #1 ?

**Comment by TechStudent10** [comment]
you pinged my alt lol

Nah, I probably won't be able to work on this.

**Comment by KendallDoesCoding** [comment]
lol..ok

**Comment by BrajBliss** [comment]
I tried doing this but couldn't get the CSS right haha. Will try later if I get time. Do not assign this to me yet, will let you know.

**Comment by KendallDoesCoding** [comment]
Hi, You can share what you did and either I or someone else will review and
try to fix the issue.

**Comment by Niravprajapati1** [comment]
You want to display -100 for every wrong answer right

**Comment by KendallDoesCoding** [comment]
Hi Nirav,

I require to display -100 for the wrong answer and +100 for the correct
answer on top of the score, like an animation.

**Comment by Sunny-25** [comment]
Assign this to me ,i can do this.

**Comment by KendallDoesCoding** [comment]
> Assign this to me ,i can do this.

Sure!

**Comment by KendallDoesCoding** [comment]
@Sunny-25 - any update?

**Comment by Sunny-25** [comment]
> @Sunny-25 - any update?
sorry man can u assign this to someone else

**Comment by SyonKuppili** [comment]
hey, could i get assigned for this issue?

**Comment by KendallDoesCoding** [comment]
> hey, could i get assigned for this issue?

assigned.
