### ISSUE TITLE
The Site can't be reached.

### ISSUE THREAD

**Issue by Akbar-Ahmed** [KendallDoesCoding/quiz#42]
### Description

Hello , when I am opening the quiz, I am seeing this The site can't be reached error. 
Any idea why it is happening. 

### Screenshots

![image](https://user-images.githubusercontent.com/70852077/226124577-41bb5c05-108b-43c9-ad5c-a3e7502f130f.png)

**Comment by KendallDoesCoding** [comment]
You are trying the old link, but I forgot to update that in README.md.

New link: https://kendalldoescoding.tech/quiz
