### ISSUE TITLE
Fix Release Workflow

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#46]
There seems to be a issue running the release.yml workflow. Right now the package-lock.js is not correct but even if that's fixed, the release.yml workflow doesn't work.

We need to fix it asap.

**Comment by swapn652** [comment]
I would like to work on this, but I don't have much experience with .yaml. Can you elaborate on what's exactly needed to be done and also provide appropriate resources to understand and work accordingly.

**Comment by KendallDoesCoding** [comment]
> I would like to work on this, but I don't have much experience with .yaml. Can you elaborate on what's exactly needed to be done and also provide appropriate resources to understand and work accordingly.

I think it's a issue with the token of the workflow (i'm not sure if I re-loaded it), so let me check.

**Comment by KendallDoesCoding** [comment]
I'll just close this issue for now, and will manually release. It's not an issue.
