### ISSUE TITLE
[FEAT] Give bonus points if answer is correct and ANSWERED QUICKLY

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#47]
If the answer is correct give 100 points (already functional), but if the user answers it fast 2-10 seconds give bonus points as follows.

2 seconds: 500 points
5 seconds: 250 points
7 seconds: 170 points
10 seconds: 50 points

**Comment by Sunny-25** [comment]
I think i can do this ,Please assign this issue to me .

**Comment by KendallDoesCoding** [comment]
> I think i can do this ,Please assign this issue to me .

Sure!

**Comment by ChiragSharma0208** [comment]
Can you assign this issue to me

**Comment by KendallDoesCoding** [comment]
> Can you assign this issue to me

@Sunny-25 - are you okay if I assign this to @ChiragSharma0208 , and you can work on #4?

**Comment by Sunny-25** [comment]
Ok no problem

**Comment by KendallDoesCoding** [comment]
@ChiragSharma0208 You are assigned!

**Comment by KendallDoesCoding** [comment]
@ChiragSharma0208 any update?
Should I assign this to @Sunny-25 ?

**Comment by raptor-07** [comment]
Hey! Can you help me find the URL where this app is deployed?

**Comment by KendallDoesCoding** [comment]
https://quiz.kendalldoescoding.tech

**Comment by ChiragSharma0208** [comment]
There is some issue in three structure of the website. Its taking longer
than expected

**Comment by KendallDoesCoding** [comment]
No worries. Take your time!

**Comment by KendallDoesCoding** [comment]
@ChiragSharma0208 - I am very sorry, I did not realize that I made a duplicate issue on this, and I already worked on this in #59 , just a few days ago.. Once again, I am very sorry.
