### ISSUE TITLE
Categorize topics by catergory

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#5]
For eg: A catergory, Games in topics

If clicked, buttons for: 
Minecraft
Roblox
Football

**Comment by KrishJ4856** [comment]
Hey @KendallDoesCoding I can do this task.
Can you please assign me the issue.

**Comment by KendallDoesCoding** [comment]
Suree

**Comment by KrishJ999** [comment]
Hey, I have raised a PR. Please review it.

**Comment by KrishJ4856** [comment]
Hey @KendallDoesCoding, I have wrongly closed the PR I made but now I have re-opened the PR. Please review it !

**Comment by KendallDoesCoding** [comment]
This was done, Forgot to close issue.
