### ISSUE TITLE
[FEAT] Add Favicon

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#53]
Add a quiz favicon, maybe like a question mark or something?

**Comment by KendallDoesCoding** [comment]
It would also be nice that per quiz, for example Tech Quiz, we put a laptop as the favicon, per quiz different favicon?

**Comment by abhinav2712** [comment]
@KendallDoesCoding assign me this, let me work

**Comment by KendallDoesCoding** [comment]
@sunny2329 - please comment on this. Please work on this with @abhinav2712 in #54.

**Comment by Gallantfarhan** [comment]
can I work on this issue? if nobody is working.

**Comment by KendallDoesCoding** [comment]
> can I work on this issue? if nobody is working.

@sunny2329 and @abhinav2712 - are you working on this?

**Comment by Gallantfarhan** [comment]
nobody assigned me yet.

**Comment by KendallDoesCoding** [comment]
> nobody assigned me yet.

I asked if @sunny2329 and @abhinav2712 who were working on this a while ago, are still working on this. If they aren't, then I will assign you.

**Comment by ujju2000** [comment]
can i work on this issue ? if nobody is working on it.

**Comment by KendallDoesCoding** [comment]
> > nobody assigned me yet.
> 
> I asked if @sunny2329 and @abhinav2712 who were working on this a while ago, are still working on this. If they aren't, then I will assign you.

Due to no reply, unassigning them.

@Gallantfarhan - do you still want to work on this or should I assign @ujju2000 ?

**Comment by ghost** [comment]
Hey, I have the fork ready with the favicon. Also, what do you mean by different favicon for each quiz? Like different favicon for each quiz (like browsers) or different favicon for each group of quizzes (like technology)

**Comment by KendallDoesCoding** [comment]
> Hey, I have the fork ready with the favicon. Also, what do you mean by different favicon for each quiz? Like different favicon for each quiz (like browsers) or different favicon for each group of quizzes (like technology)

Ok, will have a look. If we can find favicon's for each quiz page then let's do it, otherwise 1 favicon can be there for all the quiz in one catergory.

**Comment by ghost** [comment]
Sounds great!
