### ISSUE TITLE
[FEATURE] Make 2 modes of the game.

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#56]
### Description

I don't always like the negative points thing, but sometimes it's early fun.. So, I was thinking we could have 2 modes of the game, we'll make the user select when they tap play button:

- Normal Mode
- Negative Points Mode

The normal mode, will be like it was before #9 , but the negative points mode will be as it is now.

### Additional information

Any thoughts @TechStudent10, @vrindavan ?

**Comment by TechStudent10** [comment]
Sure, why not.

**Comment by BrajBliss** [comment]
LGTM

**Comment by KendallDoesCoding** [comment]
This isn't needed after adding #59 . Now, nobody gets negative points at the end unless they get all wrong.
