### ISSUE TITLE
[FEAT] Improve Design of Rating Page

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#57]
Improve Design of: http://quiz.kendalldoescoding.tech/pages/rating.html

**Comment by Shubh8899** [comment]
@KendallDoesCoding  Do you have any design or theme as a suggestion? I am interested in this but would like little more help from your side in design or theme as a suggestion.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Do you have any design or theme as a suggestion? I am interested in this but would like little more help from your side in design or theme as a suggestion.

@Shubh8899 - thanks for your interested. Although, I have already started work on this issue, I forgot to assign myself. @Shubh8899 - Please check out other issues and feel free to contribute to this project. Sorry for the inconvience.
