### ISSUE TITLE
[FEAT] Bonus Points

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#59]
- A bonus points system.

 - If the user answers within a few seconds and the answer is correct, then give bonus points as follows
     - 1 second - 1000 points
     - 5 seconds - 500 points
     - 10 seconds - 100 points

- If the user gets many answers in a row correct, then give bonus points to the user as follows
      - 2 in a row - 200 points
      - 3 in a row - 300 points
      - 5 in a row - 800 points
      - 10 in a row (for quizzes that apply) - 1200 points
      - 15 in a row (for the quizzes that apply) - 1500 points

**Comment by ghost** [comment]
@KendallDoesCoding i want to work on this
please assign this to me

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding i want to work on this please assign this to me

@ankitrajrj - I was testing something on this, assigned you.

**Comment by ghost** [comment]
@KendallDoesCoding i have some Questions regarding it please provide me your Twitter id pr discord for asking Questions ... 

Ankitraj_rj17    👈 my Twitter account

**Comment by KendallDoesCoding** [comment]
Can you ask the questions here plz?

*Thanks,*
*Kendall Does Coding*

*Portfolio <https://kendalldoescoding.gq>*
*Github <https://github.com/KendallDoesCoding>*
*Youtube* <https://kendalldoescoding.gq/codingYT>

**Comment by ghost** [comment]
@KendallDoesCoding  i want to ask in wich file I have to make contribution .. i want to know in which section I have to add A Bonus Point System .. tell the file name in wich i have to contribute

**Comment by KendallDoesCoding** [comment]
@ankitrajrj - I got this done, I was already half way done on working on this when you asked to be assigned, but I wasn't getting anywhere, I finally figured out my issue and got it sorted. Very sorry for the inconvenience.

Make sure to check out the other issues, and contribute to one! Thanks and sorry again.

**Comment by ghost** [comment]
@KendallDoesCoding okay. If you have any beginner friendly good first issue. Please inform to me i will definitely work on it

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding okay. If you have any beginner friendly good first issue. Please inform to me i will definitely work on it

@ankitrajrj - you can make a issue suggesting a quiz topic, and then work on adding the quiz topic, if you would like. :)!

**Comment by ghost** [comment]
Ya sure i will work on it
