### ISSUE TITLE
[DOCS] Add a Code of Conduct (COC)

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#6]
You have to add this COC:

[Example File in Another repo](https://github.com/InnateComm/.github/blob/main/CODE_OF_CONDUCT.md) - Contributor Covenant Code of Conduct v2

**Comment by FahimFBA** [comment]
You can assign me the task.

**Comment by KendallDoesCoding** [comment]
> You can assign me the task.

Thanks, done

**Comment by FahimFBA** [comment]
Submitted the PR.

**Comment by KendallDoesCoding** [comment]
> Submitted the PR.

Merged it in, thanks for your contribution!
