### ISSUE TITLE
Music off button does not go away if pressed once

### ISSUE THREAD

**Issue by NeevJewalkar** [KendallDoesCoding/quiz#68]
## Description
In the quiz, the button "Music Off" just sticks with the "Music On" button after clicking the off button. This results in the Music Off button being inactive.

## Proposed changes
After inspecting the code, the Music Off button doesnt have a call to get its style changed

### Screenshots

<img width="1310" alt="Screenshot 2023-07-29 at 6 47 11 PM" src="https://github.com/KendallDoesCoding/quiz/assets/140781944/799db3f1-1c9f-4fc4-b6ea-a1ecd1e40d28">

<img width="1313" alt="Screenshot 2023-07-29 at 6 46 58 PM" src="https://github.com/KendallDoesCoding/quiz/assets/140781944/04999e75-7978-43d7-a172-95ca7494eb12">

### Additional information

I will open a new PR solving this issue shortly

**Comment by KendallDoesCoding** [comment]
fixed in #69

**Comment by NeevJewalkar** [comment]
nice
