### ISSUE TITLE
[DOCS] Contributing Guidelines

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/quiz#78]
> Guys, we have some amazing ideas here. Make sure to add the quiz, if you like as I can't add all of these quizzes, but as a COMMUNITY, we can!!

There should also be a proper contributing guidelines in the README for easier entry to contribution as well as easier maintenance.

_Originally posted by @debasish-dutta in https://github.com/KendallDoesCoding/quiz/issues/32#issuecomment-1847179963_

**Comment by KendallDoesCoding** [comment]
Can you work on this @debasih-dutta

**Comment by debasish-dutta** [comment]
Sure. I'll get to it.

**Comment by adityaraute** [comment]
Shouldn't this issue be closed if the PR has been merged?
