### ISSUE TITLE
Cannot access the quiz

### ISSUE THREAD

**Issue by adityaraute** [KendallDoesCoding/quiz#81]
### Description

I tried clicking on the Quiz Website in the README and was directed to this page. Screenshot below.
The URL seems to be misdirected.

### Screenshots

![image](https://github.com/KendallDoesCoding/quiz/assets/43912470/97a04201-f238-4fec-b98d-48cbc0075bcc)

**Comment by KendallDoesCoding** [comment]
Hi. So sorry about that, my domain has expired and when I try to renew it it says domain is already registered. I don't think it is, but it I a glitch I guess.

To access the quiz, try this for now: https://quiz-game-by-kendall.netlify.app/.

Thanks

**Comment by adityaraute** [comment]
Maybe we should modify the link in the About section

**Comment by KendallDoesCoding** [comment]
> Maybe we should modify the link in the About section

Actually, I was working on getting my domain back but you can do that for now temporarily.  Please make a Pr.

**Comment by adityaraute** [comment]
I'm not sure I can generate a PR for the About section of the repo.
Perhaps, that is restricted to the repo maintainers and owners?

**Comment by KendallDoesCoding** [comment]
Oh sorry. I thought you meant README.

**Comment by adityaraute** [comment]
I can make a change in the README too. I'll raise a PR for that.
For the About section, you'll have to do it though.
